name: python-actions-demo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
     steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        pip install flask
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
